### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Kiho** [pyoner/svelte-ts-template#6]
I can't build app in windows. Any idea?
```
PS C:\poc\svelte\svelte-app> npm run build

> svelte-ts-app@1.0.0 build C:\poc\svelte\svelte-app
> rollup -c


src/main.ts → public/bundle.js...
src/App.svelte:1:2 - error TS2304: Cannot find name 'h1'.

1 <h1>Hello {name}!</h1>
   ~~
src/App.svelte:1:5 - error TS2304: Cannot find name 'Hello'.

1 <h1>Hello {name}!</h1>
      ~~~~~
src/App.svelte:1:11 - error TS1005: ';' expected.
......
```

**Comment by pyoner** [comment]
I think it related to https://github.com/pyoner/svelte-ts-template/issues/3
But it was fixed https://github.com/pyoner/svelte-ts-template/commit/2511ef9e1cdbf8da31013c54cbfc0e01b426f888

Try the latest update

**Comment by gluax** [comment]
Latest version still produces error on Windows. Cloning repo and trying to build produces:

[!] (svelte plugin) ParseError: Unterminated regular expression
src\App.svelte
16:     name;
17: }
18: !/h1>
      ^
19:     < p >
20:     />

**Comment by pyoner** [comment]
Hi @Kiho, @gluaxspeed 
The project moved to this monorepo https://github.com/pyoner/svelte-typescript
Can you try new template? https://github.com/pyoner/svelte-typescript/tree/master/packages/template

**Comment by Kiho** [comment]
That repo works fine in windows.
Thanks.

**Comment by lacera-ep** [comment]
Still having the same issue even with the latest template referenced above.

```
 svelte-ts-template@1.0.0 autobuild D:\Temp\svelte-typescript-master (1)\svelte-typescript-master\packages\template
> rollup -c -w
rollup v1.16.2
bundles src/main.ts → public\bundle.js...
src/App.svelte:1:2 - error TS2304: Cannot find name 'h1'.
1 <h1>Hello {name}!</h1>
```

**Comment by Kiho** [comment]
@lacera-ep looks like fixed code was not published to npm.
You can try this `@kiho/svelte-ts-preprocess` if you can't wait.

**Comment by pyoner** [comment]
@lacera-ep use this repo https://github.com/pyoner/svelte-typescript/tree/master/packages/template

**Comment by pyoner** [comment]
@lacera-ep @Kiho 
Before publishing the preprocessor I'm forgot to build it
Sorry guys

**Comment by eddiepaz** [comment]
It's working now. Thank you!
